{{- if eq .Values.externalSecrets.enabled true }}
{{- range $path := .Values.externalSecrets.relativeVaultPaths }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ template "service.fullname" $ }}{{ $path | replace "/" "-" }}-vault
  annotations:
      argocd.argoproj.io/sync-wave: "-3"
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes-{{ $.Values.cluster }}
  vaultRole: {{ $.Values.cluster }}-role
  dataFrom:
    - secret/data/{{ $.Values.cluster }}/{{ template "service.fullname" $ }}{{$path}}
---
{{- end }}
{{- end }}
