{{- if .Values.hpa.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "service.fullname" . }}
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.deployment.apiVersion }}
    kind: {{ .Values.hpa.kind | default "Deployment" }}
    name: {{ template "service.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
{{- with .Values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
            type: Utilization
            averageUtilization: {{ . }}
{{- end }}
{{- with .Values.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: {{ . }}
{{- end }}
{{- end }}
