{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  name: {{ template "service.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "service.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
