{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "service.fullname" . }}-secret
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
    labels:
{{ include "service.labels.standard" . | indent 6 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
