{{- if eq .Values.serviceAccount.create true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  name: {{ template "service.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
